spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    initialization-mode: always
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
logging:
  level:
    io.r2dbc: DEBUG