spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challengedb?useSSL=false
    username: root
    password: damr.1992
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true
